{{- $volumeSecret := .Values.volumeSecret -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      {{- range $volumeSecret }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      containers:
      - env:
        - name: Revision
          value: "{{ .Release.Revision }}"
        name: {{ .Values.name }}
        image: {{ .Values.image }}
        volumeMounts:
        {{- range $volumeSecret }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: true
        {{- end }}
