{{- range .Values.ingressroute }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: {{ .certResolver }}
    domains:
    - main: "{{ .domain }}"
  routes:
  - match: Host(`{{ .domain }}`)
    kind: Rule
    services:
    - name: {{ .service }}
      port: {{ .port | default 80 }}
{{- end }}


{{- range .Values.ingressTCP }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-{{ .name }}
spec:
  entryPoints:
    - {{ .name }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .service }}
          port: {{ .port | default 9090 }}
{{- end }}